chat/routes.py
from flask import (
    Blueprint,
    request,
    render_template,
    redirect,
    url_for
)
from flask_jwt_extended import current_user

from app import db#, csrf
from login.session_time import session_time
from models import (
    Chat,
    get_chat,
    get_user,
    get_all_chat
)

message = Blueprint('message',
    __name__,
    template_folder='templates')


@message.route('/', methods=['GET', 'POST'])
@session_time
def message_index():
    another_user = ''
    username = ''
    if request.method == 'POST':
        username = request.form.to_dict().get('username')
        another_user = get_user(username=username)
        chat = get_chat(current_user, another_user)
        if not chat and (current_user and another_user and current_user != another_user):
            chat = Chat()
            for user in [current_user, another_user]:
                chat.users.append(user)
            db.session.add(chat)
            db.session.commit()
    chats = get_all_chat(current_user)
   
    if username == current_user.username:
        another_user = [i.uuid for i in chats[0].users if i.id != current_user.id]


    return render_template('chat.html',
        current_user=current_user,
        another_user=another_user,
        chats=chats,
        root_url=request.url
    )

login/routes.py
from login.session_time import user_or_anon
from flask import (
    render_template,
    Blueprint,
    session,
    request,
    redirect,
    url_for,
    flash,
    make_response
)

from app import app, db
from .forms import (
    EmailForm,
    RegistrationForm,
    LoginForm,
    ResetPasswordForm
)
from models import Knot
from utils import encrypt_string
from datetime import datetime, timedelta
from .send_email import send_email
from config import login_stamp
from flask_wtf.csrf import generate_csrf

# route user enter data to form for autorization process.
login = Blueprint('login', __name__, template_folder='templates')


@login.route('auth/', methods=['GET'])
def authentication():

    now = datetime.now()

    try:
        user = Knot.query.filter(Knot.username==request.args.get('user')).first()
        time_delta = now - user.auth_key_create

        if user.authenticated:
            return redirect('/blog/')
        elif user.auth_key == request.args.get('key') and user.check_auth_key():
            user.authenticated = 1
            db.session.commit()
            flash(u'Your email address has been verified!', 'alert alert-success')
            return redirect(url_for('login.log_in'))
        else:
            user.get_auth_key()
            db.session.commit()
            subject = "authentication"
            url = f'{request.url_root}auth/?user={user.username}&key={user.auth_key}'
            content = lambda: render_template('emails/confirmed.html', url=url)
            send_email(user.email, subject, content)
            flash(u'Time has passed, we are sending a new link', 'alert alert-danger')
            return redirect(url_for('login.log_in'))
    except Exception as e:
        print(f'Something wrong: {e.__class__}')
        return redirect(url_for('posts.index'))


@login.route('/sign_up', methods=['GET', 'POST'])
@user_or_anon
def sign_up(current_user):

    form = RegistrationForm(request.form)

    if current_user:
        return redirect('/blog/')
    elif request.method == 'POST' and form.validate_on_submit():
        try:
            user = Knot(
                f_name=form.f_name.data,
                s_name=form.s_name.data,
                username=form.username.data,
                phone_number=form.phone_number.data,
                email=form.email.data,
                password=form.password.data
            )
            if user.email != app.config.get('MAIL_USERNAME'):
                subject = "authentication"
                url = f'{request.url_root}auth/?user={user.username}&key={user.auth_key}'
                content = lambda: render_template('emails/confirmed.html', url=url)
                send_email(user.email, subject, content)
            else:
                user.admin = 1
                user.authenticated = 1
            db.session.add(user)
            db.session.commit()
            flash(u'Confirm you email', 'alert alert-warning')
        except Exception as e:
            print(f'Something wrong: {e.__class__}')
            raise e
        return redirect(url_for('login.log_in'))	
    return render_template('registration.html',
        title='Sign In',
        form=form,
        session=session,
        endpoint=request.endpoint
    )


@login.route('/log_in', methods=['POST', 'GET'])
@user_or_anon
def log_in(current_user, alert=None, redirect_url=None):
    if (referer:= request.headers.get('Referer')):
        referer = referer.split(request.host)[-1]
        referer = '/blog/' if referer == '/log_in' else referer

    form = LoginForm(request.form)
    alert = request.args.get('alert')

    if current_user:
        if referer:
            return redirect(referer)
    elif request.method == "POST" and form.validate_on_submit():
        user = Knot.query.filter_by(username=form.username.data).first()
        if user and user.password == encrypt_string(form.password.data):
            session['username'] = user.username
            session['auth'] = user.authenticated
            user.last_login = datetime.now()
            db.session.commit()
            session['last_login'] = user.last_login
            session['private_key_exp'] = user.last_login + timedelta(hours=3)
            if referer:
                return redirect(referer)
            return redirect(url_for('posts.index'))
        else:
            form.password.errors.append('Incorrect data. Please try again.')
            for f in form._fields.values():
                if f.id == 'username' and user:
                    continue
                f.data = None


    response = make_response(render_template('login.html',
        title='Log in',
        alert=alert,
        form=form,
        session=session,
        endpoint=request.endpoint,
        referer=referer if referer else ''
    ))
    response.set_cookie('access_token_cookie', '', expires=0)

    return response
    
    
# @login.route('/log_out', methods=['POST', 'GET'])
# def log_out():
#     return redirect(url_for('login.log_in'))


@login.route('/reset_password', methods=['POST', 'GET'])
def reset_password():
    if request.method == 'GET':
        if not request.args:
            form = EmailForm()
            return render_template(
                'get_email.html', title='Knots password changer', form=form)
        else:
            reset_password_key = request.args.get('reset_key')
            form = ResetPasswordForm()
            response = make_response(render_template(
                'reset_password.html', title='Knots reset password', form=form))
            response.set_cookie('reset_key', reset_password_key)
            return response
    # elif request.method == 'POST':
    #     # reset_password_key = request.args.get('reset_key')
    #     data = jwt.decode(reset_password_key, options={"verify_signature": False})
    #     pass

@login.route('/privacy_policy', methods=['GET'])
def privacy():

    return render_template('privacy.html',
        title='Privacy Policy',
        session=session,
    )

posts/routes.py
from nis import cat
from pprint import pprint
import re
from flask_jwt_extended import current_user
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    session,
    flash,
    jsonify
)

from app import db#, csrf
from .forms import PostForm, CommentForm, CategoryForm, get_category
from login.session_time import session_time, user_or_anon
from login.send_email import send_email
from login.is_email_authenticated import is_email_authenticated
from admin.admin_handler import admin_handler
from models import (
    Post,
    Tag,
    Knot,
    Comment,
    Category,
)

from .schemas import posts_schema


SUCCESSFUL = 'alert alert-success'
ERROR = 'alert alert-danger'
WARNING = "alert alert-warning"

posts = Blueprint('posts',
    __name__,
    template_folder='templates')

        
### Create post ###
'''Page with form for write Title Body and Tag. 
   Than its information put in class Post and add in db.''' 

@posts.route('/create', defaults={'category': None}, methods=['POST', 'GET'])
@posts.route('/create/<category>', methods=['POST', 'GET'])
@session_time
@is_email_authenticated
def create_post(category):
    form = PostForm(request.form)
    form.category.choices = get_category()

    if request.method == 'POST' and current_user.authenticated and form.validate_on_submit():
        try:
            post = Post(
                title=form.title.data,
                preview=form.preview.data,
                body=form.body.data,
                author=current_user.username
            )
            if form.category.data != 'ch':
                post.category_id = Category.query.filter(Category.short_name==form.category.data).first().id
            tag_list = re.sub(r'[\s, .]', ' ', form.tags.data).split()
            for i in set(tag_list):
                if Tag.query.filter_by(name=i).first():
                    tag = Tag.query.filter_by(name=i).first()
                else:
                    tag = Tag(name=i)
                post.tags.append(tag)
            if request.form['submit'] == 'draft':
                post.visible = False
            db.session.add(post)
            db.session.commit()
            try:
                subject = "Good job!"
                content = lambda: render_template('emails/post_to_email.html', post=post)
                send_email(current_user.email, subject, content)
            except Exception as e:
                print('email error:', e)
                flash(u'Post create, but not send to email', WARNING)
            flash(u'Post create', SUCCESSFUL)
        except Exception as e:
            print('some error:', e)
            flash(u'ERROR: {}'.format(e.__class__), ERROR)
            raise e
        return redirect(url_for('posts.index'))
    elif request.method == 'POST' and not current_user.authenticated:
        flash(u'Before saving the changes, you must confirm the email address.', 'alert alert-warning')
    else:
        if category:
            form.category.data = category.lower()
        return render_template('create_post.html', form=form, categories=Category.query.all())


@posts.route('/<id>/edit/', methods=['POST', 'GET'])
@session_time
@is_email_authenticated
def edit_post(id):

    post = Post.query.filter(Post.id==id, Post.author==current_user.username).first()
    fields = dict(
        title = post.title,
        body = post.body,
        preview = post.preview,
        tags=', '.join(list(str(i.name) for i in post.tags.__iter__()))
    )
    category = Category.query.get(post.category_id)
    if category:
        fields['category'] = category.short_name

    form = PostForm(**fields)
    if not category:
        form.category.choices = get_category()

    try:
        if request.form['submit'] == 'cancel':
            return redirect(url_for('posts.index'))
    except KeyError:
        pass

    if request.method == 'POST' and current_user.authenticated and current_user.username == post.author and form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.preview = form.preview.data
        if form.category.data != 'ch':
            post.category_id = Category.query.filter(Category.short_name==form.category.data).first().id
        tag_list = re.sub(r'[\s, .]', ' ', form.tags.data).split()
        post.tags.clear()
        db.session.commit()      
        for i in set(tag_list):
            if Tag.query.filter_by(name=i).first():
                tag = Tag.query.filter_by(name=i).first()
            else:
                tag = Tag(name=i)
            post.tags.append(tag)
        try:
            if request.form['submit'] == 'publish':
                post.visible = True
            db.session.commit()
            try:
                subject = "Good job!"
                content = lambda: render_template('emails/post_to_email.html', post=post)
                send_email(current_user.email, subject, content)
            except Exception as e:
                flash(u'Post create, but not send to email', WARNING)
            flash(u'Changes saved successfully', SUCCESSFUL)
        except Exception as e:
            flash(u'ERROR: {e}', ERROR)
        return redirect(url_for('posts.post_content', id=post.id))
    elif request.method == 'POST' and not current_user.authenticated:
        flash(u'Before saving the changes, you must confirm the email address.', 'alert alert-warning')
        return render_template('edit_post.html',
            post=post,
            form=form,
            categories=Category.query.all()
        )
    else:
        return render_template('edit_post.html',
            post=post,
            form=form,
            categories=Category.query.all()
        )

@posts.route('/<id>/delete/', methods=['POST', 'GET'])
@session_time
def delete_post(id):
    post = Post.query.filter(Post.id==id).filter(Post.visible==True).first()

    if current_user.username == post.author:
        try:
            post.invisible()
            db.session.commit()
            flash(u'Post moved to trash', WARNING)
        except Exception as e:
            flash(u'Something happened', ERROR)
    return redirect('/blog/')


@posts.route('/', methods=['GET'])
@user_or_anon
def index(current_user):

    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    posts = Post.query.order_by(db.desc(Post.created)).filter(Post.visible==True)

    for post in posts:
        post.body = re.sub(r'\\r|\\n|\\t|<ul>|<li>|</ul>|</li>|<table|<tr|<td|</table|</td|</tr', '', ''.join(i for i in post.body.split("\n")[:3]))

    pages = posts.paginate(page=page, per_page=6, max_per_page=6)
    posts = posts_schema.dump(pages.items)

    return render_template('index_posts.html',
        posts=posts,
        pages=pages,
        title="Blog",
        categories=Category.query.all(),
        с='',
        root_url=f'{request.url_root}',
        user=current_user
    )


@posts.route('/<id>', methods=['POST', 'GET'])
@user_or_anon
def post_content(current_user, id):
    try:
        post = Post.query.filter(Post.id==id).first()
        if (not current_user or current_user.username != post.author) and not post.visible:
            post = None
        tags = post.tags
        time = post.created_to_str()
        author = post.author
        comments = post.comments
    except Exception as e:
        print(e)
        return redirect('/blog/')

    form = CommentForm(request.form)

    if request.method == 'POST' and form.validate_on_submit():
        if current_user and current_user.authenticated:
            try:
                comment = Comment(
                    text=form.text.data,
                    author_id=current_user.id,
                    post_id=post.id
                )
                db.session.add(comment)
                db.session.commit()
                flash('Comment added', SUCCESSFUL)
            except Exception as e:
                print(f'Something wrong\n{e.__class__}')
                raise e
            return redirect(url_for('posts.post_content', id=id))
        else:
            return redirect(url_for('login.log_in'))

    return render_template('post_content.html',
        post=post,
        tags=tags,
        time=time,
        author=author,
        user=current_user,
        comments=comments,
        form=form,
        categories=Category.query.all()
    )


@posts.route('/tag/<slug>/')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.name == slug).first()
    posts = Post.query.filter(Post.tags.contains(tag)).filter(Post.visible==True)
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    pages = posts.paginate(page=page, per_page=6)

    return render_template('index_posts.html',
        tag=tag,
        pages=pages,
        title=tag.name,
        content_title=f'#{tag}',
        categories=Category.query.all()
    )


@posts.route('/category/add', methods=['GET', 'POST'])
@admin_handler
@session_time
def category_create():

    form = CategoryForm(request.form)

    if 'username' in session:
        if request.method == 'POST' and form.validate_on_submit():
            try:
                category = Category(
                    name=form.name.data,
                    short_name=form.short_name.data
                )
                db.session.add(category)
                db.session.commit()
                flash('Category create', SUCCESSFUL)
            except Exception as e:
                print(f'Something wrong\n{e.__class__}')
            return redirect(url_for('admin.admin_index'))
    else:
        return redirect('/log_in')


@posts.route('/category/<slug>/', methods=['GET'])
def category_detail(slug):


    isApi = request.headers.get('apiRequest')

    category = Category.query.filter(Category.name==slug).first()
    if not category:

templates/base.html
<!DOCTYPE html>
<html lang='en'>

<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width initial-scale=1.0" http-equiv="cache-control">
    <title>
        {% block title %}
        {% endblock %}
    </title>

    {% block seo %}
    {% endblock %}
    
    <link rel="shortcut icon" href="/static/img/brain.svg">

    <link href="/static/scripts/libs/code_highlight/styles/monokai-sublime.css" rel="stylesheet" >
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="/static/fonts/free-fa-solid-900.woff2" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet"  type="text/css">

    <script 
        src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script 
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script 
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    <script src="/static/scripts/libs/jQuery.min.js"></script>
    <script src="/static/scripts/libs/fontAwesome.js"></script>
    {% if dev_anv %}
        <script src="/static/scripts/libs/vue.js"></script>
    {% else %}
        <script src='/static/scripts/libs/vue.prod.js'></script>
    {% endif %}
    <script src="/static/scripts/libs/vueUtils.js"></script>
    <script src="/static/scripts/libs/lodash.js"></script>
    <script src='/static/scripts/storage.js'></script>
    <script src="/static/scripts/libs/moment.js"></script>
    <script src='/static/scripts/utils.js'></script>

    {% block scripts %}

    {% endblock %}
    
</head>

<body>
    <div class='center'>
        <div id='base' class="post-header">
            <div id="header_inner">
                <div class='media_search header_search'>
                    <form action="{{ url_for('posts.search', slug=request.args.get('q', ' ')) }}" method="GET">
                        <div class="search-container">
                            <input id="submit_search" type="submit" value=" " class="icon_search">
                            <span style="margin: auto;">
                                <input autocomplete="off" class="q" type="text" name="q" value="{{ q }}"
                                    placeholder="Search" data-autofocus="">
                            </span>
                        </div>

                        <div class="navbar navbar-light profile-button">
                            <button v-if="store.state.isAuth" class="navbar-profile" id="dropdownMenuButton" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                <i id='user_button' class="fas fa-user-circle with_user"></i>
                            </button>
                            <button v-else class="navbar-profile" id="dropdownMenuButton" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false" title="anonymous">
                                <i id='user_button' class="fas fa-user without_user"></i>
                            </button>

                            <div class="collapse navbar-collapse drop-menu dropdown-menu" id="navbarTogglerDemo02"
                                aria-labelledby="dropdownMenuButton">
                                <ul class="navbar-nav ">
                                    <li v-if="store.state.isAuth" class="dropdown-item"
                                        style="display: flex; align-items: center; margin: auto;">
                                        <a class="nav-link disable-scale" href=" {{ url_for('posts.index') }}">Blog</a>
                                        <a class="nav-link" style="font-size: 30px; margin-left: auto;"
                                            href="{{ url_for('posts.create_post', category=None) }}">&#x270d;</a>
                                    </li>
                                    <li v-else class="dropdown-item">
                                        <a class="nav-link" href=" {{ url_for('posts.index') }}">Blog</a>
                                    </li>

                                    <li v-if="store.state.isAuth" class="dropdown-item">
                                        <a class="nav-link" href="{{ url_for('message.message_index') }}"
                                            title="Profile">Chat</a>
                                    </li>

                                    <li v-if="store.state.isAuth" class="dropdown-item">
                                        <a class="nav-link"
                                            ref="profileLink"
                                            style="cursor: default;"
                                            v-on:click="toProfile"
                                        >Profile</a>
                                    </li>
                                    <li v-if="store.state.isAuth" class="dropdown-item">
                                        <a class="nav-link" style="cursor: default;" v-on:click="logOut">Log out</a>
                                    </li>

                                    <li v-if="!store.state.isAuth" class="dropdown-item">
                                        <a class="nav-link" href="{{ url_for('login.sign_up') }}">Sign up</a>
                                    </li>
                                    <li v-if="!store.state.isAuth" class="dropdown-item">
                                        <a class="nav-link" href="{{ url_for('login.log_in') }}">Login</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        {% if categories %}
                            <div class="category-show">
                                <select id="category-value-select"
                                    data-url="{{ url_for('posts.category_detail', slug='empty')}}" name="c">
                                    {% if c %}
                                        <option style='color: #4ea08a;;' value='none'>All category</option>
                                        <option selected="selected">{{ c.name }}</option>
                                        {% for category in categories %}
                                            {% if category.name != c.name %}
                                                <option value="{{ category.name }}">{{ category.name }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    {% else %}
                                        <option style='color: #4ea08a;;' value='none'>All category</option>
                                        {% for category in categories %}
                                            <option value="{{ category.name }}">{{ category.name }}</option>
                                        {% endfor %}
                                    {% endif %}
                                </select>
                            </div>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>


        <div class="post-body">
            <div class="content_title">
                {% block content_title %}
                {% endblock %}
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                    <div id='alert-msg' class="{{ category }}" role="alert">
                        {{ message }}
                    </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}
            {% endblock %}

        </div>
        {% block logo %}
        
        {% endblock %}
        <div id="toTop"><i class="fas fa-chevron-up"></i></div>
        <br>
    </div>
    <script src="/static/scripts/constants.js"></script>
    <script src="/static/scripts/main.js"></script>
    <script src="/static/scripts/libs/dateFormatter.js"></script>
    <script src="/static/scripts/containers/base.js"></script>
    <script>
        $("div#alert-msg").fadeOut(4000);
    </script>
</body>

</html>

templates/post_content.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block seo %}
    <meta name="description" content="{{ post.preview }}">
    <meta name="keywords" content="{{ tags|map(attribute='name')|join(', ') }}">
    <meta name="author" content="{{ post.author }}">
{% endblock %}

{% block content_title %}
<div class="post-content-title">
        <span><h1 class="post_content_title_h1">{{ post.title }}</h1></span>
        {% if user.username == post.author %}
            <div>
                <a class="far fa-edit" style="font-size: 20px; margin-top: 2px; margin-left: 5px; color: #d5d1ca; text-decoration: none;" href="{{ url_for('posts.edit_post', id=post.id) }}" title="Edit post"></a>
                {% if post.visible %}
                    <a class="fas fa-trash-alt" style="font-size: 20px; margin-top: 2px; margin-left: 5px; color: #d5d1ca; text-decoration: none;" href="{{ url_for('posts.delete_post', id=post.id) }}" title="Delete post"></a>
                {% endif %}
            </div>
        {% endif %}
</div>
{% endblock %}

{% block content %}
    <div class="tags">
        <div class="post-info">
            <div class="post-title-author">
                <a href="{{ url_for('user_profile.get_user_data', slug=author or 'anonymous')}}">
                    @{{ author }}
                </a>
            </div>
            <div>
                <span class="post-title-sep-dot">&#8901;</span>
            </div>
            <div class="post-title-created">
                {{ time }}
            </div>
        </div>
    </div>
    
    <hr class='content_title_hr'>

    <div class="post-body-content">
        {{ post.body|safe }}
        <div class="end-post-content">. . .</div>
    </div>
    <div class="tag-buttons">
        <h4 style="margin-bottom: 0rem;padding: .0em .2em .0em .0em;">Tags:</h4>
        {% for tag in tags %}
            <a class="tag-button" href="{{ url_for('posts.tag_detail', slug=tag.name)}}"><span class="tag badge-pill badge-secondary">{{ tag.name }}</span></a>
        {% endfor %}
    </div>
    <hr class='tag-buttons'>
    <br>
    <div class="comments">
        <div>
            <h4>Comments <span style="color: #17a2b8;">{{ comments|length }}</span>:</h4>
        </div>

        <div>
            {% if comments %}
                {% for comment in comments %}
                    <div class="main-content" style="padding-top: 10px; font-size: 20px; position: block; word-wrap: break-word;">
                        <div class="post-comment-author">
                            <img class="user_comment_avatar" src="{{ comment.author.avatar(size=25) }}">
                            <a href="{{ url_for('user_profile.get_user_data', slug=comment.author.username or 'anonymous')}}" >
                                @{{ comment.author.username }}
                            </a>
                            <div class="post-comment-created">
                                {{ comment.created_to_str() }}
                            </div>
                        </div>
                        <div style="font-size: 1.1rem; margin-left: 35px">
                            {{ comment.text }}
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        <br>

        <div>
            <form action="" method="POST">
                <a name="comments"></a>
                {% for field in form %}
                <div class="form-group">
                    {{ field(class='form-control form-value-comment textarea', placeholder='write comment') }}
                    {% for error in field.errors %}
                    <span style="color: red;">{{ error }}</span>
                    {% endfor %}
                </div>
                {% endfor %}
            
                <div class="" style="text-align: left; margin-left: auto;
                margin-right: auto;">
                    <button type="submit" class="btn btn-info">Add comment</button>
                </div>
            </form>
        </div>
    </div>

    <script src="/static/scripts/libs/code_highlight/highlight.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

templates/registration.html
{% extends 'index.html' %}

{% block title %}
	{{ title }}
{% endblock %}

{% block content_title %}
	
{% endblock %}

{% block data %}
        <div class='container-fluid text-center body_'>
		<form class='form-signin' action="" method="POST">
			{% for field in form %}
				{{ field(class='form-control', autocomplete='off', placeholder=field.id) }}
				{% for error in field.errors %}
           			<div class="alert alert-danger" role="alert">
 						{{ error }}
					</div>
           		{% endfor %}
			{% endfor %}
            <button class="btn btn-lg btn-primary btn-registration" type="submit">Sign Up</button>
			<div style="margin-top: 5px; font-size: 11px;">
				By signing up you agree to the <a href={{ url_for('login.privacy') }}>Privacy Policy</a>
			</div>
			<div class="new-user-reg">
				<a href="{{ url_for('login.log_in') }}">Sign in</a>
			</div>
		</form>
		</div>

{% endblock %}